# -*- coding: utf-8 -*-
"""
Created on Thu Jun 11 15:27:43 2020

@author: chmar
"""


#a script for processing GEOS data using GEOS2WRF. It is designed to use the same folder structure as the download_wrapper
#This script runs GEOSWPS but does not run any of the utilities because of timing issues. That will be yet another high level script. 
#This is a fairly uninteresting script


# Import necessary libraries
import os
from namelist_geos_scripts import GEOS_start, GEOS_end, path_to_storm, script_folder, net_id
# Change working directory
os.chdir(script_folder)


#write and submit an sbatch job for each field:

#constants file:

sbatch=open("GEOS_CONST.sbatch", "w")
sbatch.write("#!/bin/bash \n")
sbatch.write("#SBATCH --nodes=1 \n")
sbatch.write("#SBATCH --job-name=GCONST \n")
sbatch.write("#SBATCH --output=GCONST.out \n")
sbatch.write("#SBATCH --error=GCONST.err\n")
sbatch.write("#SBATCH --time=5:00:00\n")
sbatch.write("#SBATCH --mem=10GB\n")
sbatch.write("#SBATCH --ntasks-per-node=20\n")
sbatch.write("#SBATCH --cpus-per-task=1\n")
sbatch.write("#SBATCH --mail-type=END\n")
sbatch.write("#SBATCH --mail-user="+ str(net_id) + "@nyu.edu\n")
sbatch.write("cd " +str(script_folder) + "\n")
sbatch.write("module load openmpi/intel/3.1.3\n")
sbatch.write("module load intel/17.0.1\n")
sbatch.write("module load openmpi/intel/3.1.3\n")
sbatch.write("module load netcdf/intel/4.4.1.1\n")
sbatch.write("module load libpng/intel/1.6.29\n")
sbatch.write("module load jasper/intel/2.0.14\n")
sbatch.write("module load openjpeg/intel/2.1.2\n")
sbatch.write("module load zlib/intel/1.2.8\n")
sbatch.write("module load hdf5/intel/1.8.21\n")
sbatch.write("module load szip/intel/2.1.1\n")
sbatch.write("module load hdf/intel/4.2.12\n")
sbatch.write("module load hdf/intel/4.2.6\n")
sbatch.write("module load netcdf/intel/4.1.1\n")
sbatch.write("module load zlib/intel/1.2.8\n")
sbatch.write("module load jpeg/intel/9b\n")
sbatch.write("module load python3/intel/3.7.3\n")
sbatch.write("python GEOS_CONST.py &> log.GCONST\n")
sbatch.close()
# sbatch=open("GEOS_CONST.sbatch", "r")
# test=sbatch.read()
# print(test)


command1='sbatch GEOS_CONST.sbatch'
os.system(command1)

#Height:
sbatch=open("GEOS_H.sbatch", "w")
sbatch.write("#!/bin/bash \n")
sbatch.write("#SBATCH --nodes=1 \n")
sbatch.write("#SBATCH --job-name=GH \n")
sbatch.write("#SBATCH --output=GH.out \n")
sbatch.write("#SBATCH --error=GH.err\n")
sbatch.write("#SBATCH --time=15:00:00\n")
sbatch.write("#SBATCH --mem=100GB\n")
sbatch.write("#SBATCH --ntasks-per-node=20\n")
sbatch.write("#SBATCH --cpus-per-task=1\n")
sbatch.write("#SBATCH --mail-type=END\n")
sbatch.write("#SBATCH --mail-user="+ str(net_id) + "@nyu.edu\n")
sbatch.write("cd " +str(script_folder) + "\n")
sbatch.write("module load openmpi/intel/3.1.3\n")
sbatch.write("module load intel/17.0.1\n")
sbatch.write("module load openmpi/intel/3.1.3\n")
sbatch.write("module load netcdf/intel/4.4.1.1\n")
sbatch.write("module load libpng/intel/1.6.29\n")
sbatch.write("module load jasper/intel/2.0.14\n")
sbatch.write("module load openjpeg/intel/2.1.2\n")
sbatch.write("module load zlib/intel/1.2.8\n")
sbatch.write("module load hdf5/intel/1.8.21\n")
sbatch.write("module load szip/intel/2.1.1\n")
sbatch.write("module load hdf/intel/4.2.12\n")
sbatch.write("module load hdf/intel/4.2.6\n")
sbatch.write("module load netcdf/intel/4.1.1\n")
sbatch.write("module load zlib/intel/1.2.8\n")
sbatch.write("module load jpeg/intel/9b\n")
sbatch.write("module load python3/intel/3.7.3\n")
sbatch.write("python GEOS_H.py &> log.GH\n")
sbatch.close()

command2='sbatch GEOS_H.sbatch'
os.system(command2)

#MET1:

sbatch=open("GEOS_MET1.sbatch", "w")
sbatch.write("#!/bin/bash \n")
sbatch.write("#SBATCH --nodes=1 \n")
sbatch.write("#SBATCH --job-name=GMET1 \n")
sbatch.write("#SBATCH --output=GMET1.out \n")
sbatch.write("#SBATCH --error=GMET1.err\n")
sbatch.write("#SBATCH --time=15:00:00\n")
sbatch.write("#SBATCH --mem=100GB\n")
sbatch.write("#SBATCH --ntasks-per-node=20\n")
sbatch.write("#SBATCH --cpus-per-task=1\n")
sbatch.write("#SBATCH --mail-type=END\n")
sbatch.write("#SBATCH --mail-user="+ str(net_id) + "@nyu.edu\n")
sbatch.write("cd " +str(script_folder) + "\n")
sbatch.write("module load openmpi/intel/3.1.3\n")
sbatch.write("module load intel/17.0.1\n")
sbatch.write("module load openmpi/intel/3.1.3\n")
sbatch.write("module load netcdf/intel/4.4.1.1\n")
sbatch.write("module load libpng/intel/1.6.29\n")
sbatch.write("module load jasper/intel/2.0.14\n")
sbatch.write("module load openjpeg/intel/2.1.2\n")
sbatch.write("module load zlib/intel/1.2.8\n")
sbatch.write("module load hdf5/intel/1.8.21\n")
sbatch.write("module load szip/intel/2.1.1\n")
sbatch.write("module load hdf/intel/4.2.12\n")
sbatch.write("module load hdf/intel/4.2.6\n")
sbatch.write("module load netcdf/intel/4.1.1\n")
sbatch.write("module load zlib/intel/1.2.8\n")
sbatch.write("module load jpeg/intel/9b\n")
sbatch.write("module load python3/intel/3.7.3\n")
sbatch.write("python GEOS_MET1.py &> log.GMET1\n")
sbatch.close()

command3='sbatch GEOS_MET1.sbatch'
os.system(command3)

#met2: 


sbatch=open("GEOS_MET2.sbatch", "w")
sbatch.write("#!/bin/bash \n")
sbatch.write("#SBATCH --nodes=1 \n")
sbatch.write("#SBATCH --job-name=GMET2 \n")
sbatch.write("#SBATCH --output=GMET2.out \n")
sbatch.write("#SBATCH --error=GMET2.err\n")
sbatch.write("#SBATCH --time=15:00:00\n")
sbatch.write("#SBATCH --mem=100GB\n")
sbatch.write("#SBATCH --ntasks-per-node=20\n")
sbatch.write("#SBATCH --cpus-per-task=1\n")
sbatch.write("#SBATCH --mail-type=END\n")
sbatch.write("#SBATCH --mail-user="+ str(net_id) + "@nyu.edu\n")
sbatch.write("cd " +str(script_folder) + "\n")
sbatch.write("module load openmpi/intel/3.1.3\n")
sbatch.write("module load intel/17.0.1\n")
sbatch.write("module load openmpi/intel/3.1.3\n")
sbatch.write("module load netcdf/intel/4.4.1.1\n")
sbatch.write("module load libpng/intel/1.6.29\n")
sbatch.write("module load jasper/intel/2.0.14\n")
sbatch.write("module load openjpeg/intel/2.1.2\n")
sbatch.write("module load zlib/intel/1.2.8\n")
sbatch.write("module load hdf5/intel/1.8.21\n")
sbatch.write("module load szip/intel/2.1.1\n")
sbatch.write("module load hdf/intel/4.2.12\n")
sbatch.write("module load hdf/intel/4.2.6\n")
sbatch.write("module load netcdf/intel/4.1.1\n")
sbatch.write("module load zlib/intel/1.2.8\n")
sbatch.write("module load jpeg/intel/9b\n")
sbatch.write("module load python3/intel/3.7.3\n")
sbatch.write("python GEOS_met2.py &> log.Gmet2\n")
sbatch.close()
command4='sbatch GEOS_met2.sbatch'
os.system(command4)


#PL:
sbatch=open("GEOS_PL.sbatch", "w")
sbatch.write("#!/bin/bash \n")
sbatch.write("#SBATCH --nodes=1 \n")
sbatch.write("#SBATCH --job-name=GPL \n")
sbatch.write("#SBATCH --output=GPL.out \n")
sbatch.write("#SBATCH --error=GPL.err\n")
sbatch.write("#SBATCH --time=15:00:00\n")
sbatch.write("#SBATCH --mem=100GB\n")
sbatch.write("#SBATCH --ntasks-per-node=20\n")
sbatch.write("#SBATCH --cpus-per-task=1\n")
sbatch.write("#SBATCH --mail-type=END\n")
sbatch.write("#SBATCH --mail-user="+ str(net_id) + "@nyu.edu\n")
sbatch.write("cd " +str(script_folder) + "\n")
sbatch.write("module load openmpi/intel/3.1.3\n")
sbatch.write("module load intel/17.0.1\n")
sbatch.write("module load openmpi/intel/3.1.3\n")
sbatch.write("module load netcdf/intel/4.4.1.1\n")
sbatch.write("module load libpng/intel/1.6.29\n")
sbatch.write("module load jasper/intel/2.0.14\n")
sbatch.write("module load openjpeg/intel/2.1.2\n")
sbatch.write("module load zlib/intel/1.2.8\n")
sbatch.write("module load hdf5/intel/1.8.21\n")
sbatch.write("module load szip/intel/2.1.1\n")
sbatch.write("module load hdf/intel/4.2.12\n")
sbatch.write("module load hdf/intel/4.2.6\n")
sbatch.write("module load netcdf/intel/4.1.1\n")
sbatch.write("module load zlib/intel/1.2.8\n")
sbatch.write("module load jpeg/intel/9b\n")
sbatch.write("module load python3/intel/3.7.3\n")
sbatch.write("python GEOS_PL.py &> log.GPL\n")
sbatch.close()
command5='sbatch GEOS_PL.sbatch'
os.system(command5)


#Now QV
sbatch=open("GEOS_QV.sbatch", "w")
sbatch.write("#!/bin/bash \n")
sbatch.write("#SBATCH --nodes=1 \n")
sbatch.write("#SBATCH --job-name=GQV \n")
sbatch.write("#SBATCH --output=GQV.out \n")
sbatch.write("#SBATCH --error=GQV.err\n")
sbatch.write("#SBATCH --time=15:00:00\n")
sbatch.write("#SBATCH --mem=100GB\n")
sbatch.write("#SBATCH --ntasks-per-node=20\n")
sbatch.write("#SBATCH --cpus-per-task=1\n")
sbatch.write("#SBATCH --mail-type=END\n")
sbatch.write("#SBATCH --mail-user="+ str(net_id) + "@nyu.edu\n")
sbatch.write("cd " +str(script_folder) + "\n")
sbatch.write("module load openmpi/intel/3.1.3\n")
sbatch.write("module load intel/17.0.1\n")
sbatch.write("module load openmpi/intel/3.1.3\n")
sbatch.write("module load netcdf/intel/4.4.1.1\n")
sbatch.write("module load libpng/intel/1.6.29\n")
sbatch.write("module load jasper/intel/2.0.14\n")
sbatch.write("module load openjpeg/intel/2.1.2\n")
sbatch.write("module load zlib/intel/1.2.8\n")
sbatch.write("module load hdf5/intel/1.8.21\n")
sbatch.write("module load szip/intel/2.1.1\n")
sbatch.write("module load hdf/intel/4.2.12\n")
sbatch.write("module load hdf/intel/4.2.6\n")
sbatch.write("module load netcdf/intel/4.1.1\n")
sbatch.write("module load zlib/intel/1.2.8\n")
sbatch.write("module load jpeg/intel/9b\n")
sbatch.write("module load python3/intel/3.7.3\n")
sbatch.write("python GEOS_QV.py &> log.GQV\n")
sbatch.close()

command6='sbatch GEOS_QV.sbatch'
os.system(command6)

#now T
sbatch=open("GEOS_T.sbatch", "w")
sbatch.write("#!/bin/bash \n")
sbatch.write("#SBATCH --nodes=1 \n")
sbatch.write("#SBATCH --job-name=GT \n")
sbatch.write("#SBATCH --output=GT.out \n")
sbatch.write("#SBATCH --error=GT.err\n")
sbatch.write("#SBATCH --time=15:00:00\n")
sbatch.write("#SBATCH --mem=100GB\n")
sbatch.write("#SBATCH --ntasks-per-node=20\n")
sbatch.write("#SBATCH --cpus-per-task=1\n")
sbatch.write("#SBATCH --mail-type=END\n")
sbatch.write("#SBATCH --mail-user="+ str(net_id) + "@nyu.edu\n")
sbatch.write("cd " +str(script_folder) + "\n")
sbatch.write("module load openmpi/intel/3.1.3\n")
sbatch.write("module load intel/17.0.1\n")
sbatch.write("module load openmpi/intel/3.1.3\n")
sbatch.write("module load netcdf/intel/4.4.1.1\n")
sbatch.write("module load libpng/intel/1.6.29\n")
sbatch.write("module load jasper/intel/2.0.14\n")
sbatch.write("module load openjpeg/intel/2.1.2\n")
sbatch.write("module load zlib/intel/1.2.8\n")
sbatch.write("module load hdf5/intel/1.8.21\n")
sbatch.write("module load szip/intel/2.1.1\n")
sbatch.write("module load hdf/intel/4.2.12\n")
sbatch.write("module load hdf/intel/4.2.6\n")
sbatch.write("module load netcdf/intel/4.1.1\n")
sbatch.write("module load zlib/intel/1.2.8\n")
sbatch.write("module load jpeg/intel/9b\n")
sbatch.write("module load python3/intel/3.7.3\n")
sbatch.write("python GEOS_T.py &> log.GT\n")
sbatch.close()
command7='sbatch GEOS_T.sbatch'
os.system(command7) 


#now U
sbatch=open("GEOS_U.sbatch", "w")
sbatch.write("#!/bin/bash \n")
sbatch.write("#SBATCH --nodes=1 \n")
sbatch.write("#SBATCH --job-name=GU \n")
sbatch.write("#SBATCH --output=GU.out \n")
sbatch.write("#SBATCH --error=GU.err\n")
sbatch.write("#SBATCH --time=15:00:00\n")
sbatch.write("#SBATCH --mem=100GB\n")
sbatch.write("#SBATCH --ntasks-per-node=20\n")
sbatch.write("#SBATCH --cpus-per-task=1\n")
sbatch.write("#SBATCH --mail-type=END\n")
sbatch.write("#SBATCH --mail-user="+ str(net_id) + "@nyu.edu\n")
sbatch.write("cd " +str(script_folder) + "\n")
sbatch.write("module load openmpi/intel/3.1.3\n")
sbatch.write("module load intel/17.0.1\n")
sbatch.write("module load openmpi/intel/3.1.3\n")
sbatch.write("module load netcdf/intel/4.4.1.1\n")
sbatch.write("module load libpng/intel/1.6.29\n")
sbatch.write("module load jasper/intel/2.0.14\n")
sbatch.write("module load openjpeg/intel/2.1.2\n")
sbatch.write("module load zlib/intel/1.2.8\n")
sbatch.write("module load hdf5/intel/1.8.21\n")
sbatch.write("module load szip/intel/2.1.1\n")
sbatch.write("module load hdf/intel/4.2.12\n")
sbatch.write("module load hdf/intel/4.2.6\n")
sbatch.write("module load netcdf/intel/4.1.1\n")
sbatch.write("module load zlib/intel/1.2.8\n")
sbatch.write("module load jpeg/intel/9b\n")
sbatch.write("module load python3/intel/3.7.3\n")
sbatch.write("python GEOS_U.py &> log.GU\n")
sbatch.close()
command8='sbatch GEOS_U.sbatch'
os.system(command8)


#now V
sbatch=open("GEOS_V.sbatch", "w")
sbatch.write("#!/bin/bash \n")
sbatch.write("#SBATCH --nodes=1 \n")
sbatch.write("#SBATCH --job-name=GV \n")
sbatch.write("#SBATCH --output=GV.out \n")
sbatch.write("#SBATCH --error=GV.err\n")
sbatch.write("#SBATCH --time=15:00:00\n")
sbatch.write("#SBATCH --mem=100GB\n")
sbatch.write("#SBATCH --ntasks-per-node=20\n")
sbatch.write("#SBATCH --cpus-per-task=1\n")
sbatch.write("#SBATCH --mail-type=END\n")
sbatch.write("#SBATCH --mail-user="+ str(net_id) + "@nyu.edu\n")
sbatch.write("cd " +str(script_folder) + "\n")
sbatch.write("module load openmpi/intel/3.1.3\n")
sbatch.write("module load intel/17.0.1\n")
sbatch.write("module load openmpi/intel/3.1.3\n")
sbatch.write("module load netcdf/intel/4.4.1.1\n")
sbatch.write("module load libpng/intel/1.6.29\n")
sbatch.write("module load jasper/intel/2.0.14\n")
sbatch.write("module load openjpeg/intel/2.1.2\n")
sbatch.write("module load zlib/intel/1.2.8\n")
sbatch.write("module load hdf5/intel/1.8.21\n")
sbatch.write("module load szip/intel/2.1.1\n")
sbatch.write("module load hdf/intel/4.2.12\n")
sbatch.write("module load hdf/intel/4.2.6\n")
sbatch.write("module load netcdf/intel/4.1.1\n")
sbatch.write("module load zlib/intel/1.2.8\n")
sbatch.write("module load jpeg/intel/9b\n")
sbatch.write("module load python3/intel/3.7.3\n")
sbatch.write("python GEOS_V.py &> log.GV\n")
sbatch.close()

command9='sbatch GEOS_V.sbatch'
os.system(command9)


